- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: deezer
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: deezer
    state: absent

- name: Create deezer directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/deezer

- name: Create and start container
  docker_container:
    name: deezer
    image: bocki/deezloaderrmx
    pull: yes
    published_ports:
      - "127.0.0.1:1730:1730"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "deezer.{{ user.domain }}"
      VIRTUAL_PORT: 1730
      LETSENCRYPT_HOST: "deezer.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      REDIRECT_URI: "https://deezer.{{ user.domain }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/deezer:/config"
      - "/mnt/:/mnt"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - deezer
    purge_networks: yes
    restart_policy: always
    state: started
